FROM golang:alpine AS builder
LABEL stage=builder

RUN apk add --no-cache gcc libc-dev

WORKDIR /workspace

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix -o ${MODULE_NAME}

FROM alpine AS final

ENV ENV=dev

WORKDIR /src

COPY --from=builder /workspace/go-server-starter .
COPY --from=builder /workspace/_envs/env_${ENV}.yaml ./_envs/

CMD [ "./go-server-starter" ]

EXPOSE 9000


